### ISSUE TITLE
Question regarding resistors

### ISSUE THREAD

**Issue by Maarten112** [kh4/FSK_modem#3]
Dear kh4,

Not really an issue but a question.

At first: thank you so much for designing the circuit. I've printed the pcb and it looks great.   

I looked at the datasheet of the TCM3105 but I can't really understand what the different voltages on pin 7 and 10 (RXB and CDL) exactly do and how to calculate them. 

Could you please tell me how critical the resistor values of 5,6K, 18K and 33K are? Is it ok to use 5% tolerance resistors of should they be really 1%?

Thanks for all your work!

**Comment by kh4** [comment]
5% should is fine.

The voltages are used to tune the receiving side circuit, the way I come up with the values was to use trimmers on RXB and CDL, tune with scope and then measure voltages. Then I searched for set of common resistors that give nearly same output voltages.

**Comment by Maarten112** [comment]
Dear kh4,

Thank you so much for your reply! I already thought using a scope and a variable resistor was the only way to get the RXB and CDL best as possible for the receiving circuit. Unfortunately I don't own a scope but only a logic analyzer...so couldn't measure it:-) 

Thanks again for all your work, I can't wait to try the modems! Only have to wait for the TCM3105 now:)
